### ISSUE TITLE
Fail on large files

### ISSUE THREAD

**Issue by W-A-James** [W-A-James/cellular#1]
For some reason the gif formatting fails when creating larger files (either many frames or large images)

**Comment by W-A-James** [comment]
When running on files of size 320x320 with 10 steps, starting with a random seed, sometimes fails with message:

```
2021-01-18T04:28:23Z ERROR ca_110::image_manip::tests] Failed to read frame 0: Io(Custom { kind: InvalidData, error: "InvalidCode" })
test image_manip::tests::test_build_gif ... FAILED

failures:

---- image_manip::tests::test_build_gif stdout ----
thread 'image_manip::tests::test_build_gif' panicked at 'Io(Custom { kind: InvalidData, error: "InvalidCode" })', src/image_manip.rs:268:25
```

Sometimes fails with message:

```
2021-01-18T04:30:12Z ERROR ca_110::image_manip::tests] Failed to read frame 0: Format(DecodingFormatError { underlying: "image truncated" })
test image_manip::tests::test_build_gif ... FAILED

failures:

---- image_manip::tests::test_build_gif stdout ----
thread 'image_manip::tests::test_build_gif' panicked at 'Format(DecodingFormatError { underlying: "image truncated" })', src/image_manip.rs:268:25
```

**Comment by W-A-James** [comment]
Try to figure out the state of the underlying bitmap when these errors occur and try to figure out if there are any other issues with the bitmap implementation
